#include <iostream>
#include <ctime>   // Required for time()

int main() {
    // Variable Declaration 
    int number_p;    // Stores the player's current guess
    int computer_p;  // Stores the target number generated by the computer
    int tries = 0;   // Counter for the number of attempts

    // Seed the random number generator using the current system time
    // This ensures we get a different number every time the program runs
    srand(static_cast<unsigned int>(time(0)));

    // Generate a random number between 1 and 100
    // rand() % 100 gives 0-99; adding 1 shifts the range to 1-100
    computer_p = rand() % 100 + 1;

    std::cout << "--- Guess the Number Game ---\n";
    
    // Initial input to start the game
    std::cout << "Choose a number between 1 and 100: ";
    std::cin >> number_p;

    // do-while loop: Executes at least once and continues until the guess is correct
    do {
        tries++; // Increment attempts at the start of each evaluation

        // Logic to provide feedback on the guess
        if (number_p > computer_p) {
            std::cout << "Too high! Go lower.\n";
        }
        else if (number_p < computer_p) {
            std::cout << "Too low! Go higher.\n";
        }
        else {
            // This block executes only if number_p == computer_p
            std::cout << "Correct! You got it.\n";
        }

        // If the guess was wrong, ask for the next number before checking the loop condition again
        if (number_p != computer_p) {
            std::cout << "Enter your next guess: ";
            std::cin >> number_p;
        }

    } while (number_p != computer_p); // Loop terminates when the user guesses correctly

    // Final game stats
    std::cout << "Congratulations! You guessed it in " << tries << " tries.\n";

    return 0; // Exit program successfully
}
